### ISSUE TITLE
Support arm64 for termux android 

### ISSUE THREAD

**Issue by drunkod** [WMSPanel/nimble-docker#1]
Please add support arm64 for termux android.

Error build:
 > [linux/arm64  8/10] RUN	APT-GET install nimble nimble-srt-1.5 -y:

#23 10.55 Reading state information...
#23 10.86 E: Unable to locate package nimble
#23 10.86 E: Unable to locate package nimble-srt-1.5
#23 10.86 E: Couldn't find any package by glob 'nimble-srt-1.5'
#23 10.86 E: Couldn't find any package by regex 'nimble-srt-1.5'
------
Dockerfile:18
--------------------
  16 |     RUN	apt-get update -y
  17 |     
  18 | >>> RUN	apt-get install nimble nimble-srt-1.5 -y
  19 |     
  20 |     
--------------------
ERROR: failed to solve: process "/bin/sh -c apt-get install nimble nimble-srt-1.5 -y" did not complete successfully: exit code: 100
Error: buildx failed with: ERROR: failed to solve: process "/bin/sh -c apt-get install nimble nimble-srt-1.5 -y" did not complete successfully: exit code: 100

**Comment by maxtomilov** [comment]
Hello @drunkod,

Which Dockerfile did you use in this case? What is the output of "uname -a" executed in docker container running in termux andriod?

Thank you.
